#!/usr/bin/env bash
set -euo pipefail

if [[ -f "$(dirname "$0")/backend.tf" ]]; then
  read -rp "Setup already run. Re-run and overwrite? [y/N]: " CONFIRM
  [[ "$CONFIRM" =~ ^[Yy]$ ]] || exit 0
fi

# Terraform comes from mise.toml, so setup uses the pinned version even if mise isn't active in this shell.
command -v mise      &>/dev/null || { echo "Error: mise is not installed. See the setup steps in the root Readme."; exit 1; }
command -v az        &>/dev/null || { echo "Error: azure CLI is not installed."; exit 1; }

# We use the project name for the storage account, so we keep it short to avoid hitting Azure's 24 character limit when combined with the suffix.
read -rp "Project name (3-18 chars, lowercase letters and numbers only): " PROJECT_NAME

if [[ ! "$PROJECT_NAME" =~ ^[a-z0-9]{3,18}$ ]]; then
  echo "Error: invalid project name."; exit 1
fi

read -rp "Azure location (leave blank for canadacentral): " LOCATION
LOCATION="${LOCATION:-canadacentral}"

read -rp "Subscription ID: " SUBSCRIPTION_ID

if [[ -z "$SUBSCRIPTION_ID" ]]; then
  echo "Error: subscription ID cannot be empty."; exit 1
fi

az config set core.login_experience_v2=off # Disables the subscription selector feature
az login --only-show-errors
az account set --subscription "$SUBSCRIPTION_ID"
az config set core.login_experience_v2=on # Re-enable the subscription selector for other commands

RG_NAME="${PROJECT_NAME}_tfstate_rg"
STORAGE_NAME="${PROJECT_NAME}tfstate"
CONTAINER_NAME="tfstate"

az group create             --name "$RG_NAME"        --location "$LOCATION" --output none
az storage account create   --name "$STORAGE_NAME"   --resource-group "$RG_NAME" --sku Standard_LRS --output none
az storage container create --name "$CONTAINER_NAME" --account-name "$STORAGE_NAME" --auth-mode login --output none

echo "Storage ready: $STORAGE_NAME / $CONTAINER_NAME"


cat > "$(dirname "$0")/backend.tf" <<EOF
# Auto-generated by setup.sh
terraform {
  backend "azurerm" {
    resource_group_name  = "$RG_NAME"
    storage_account_name = "$STORAGE_NAME"
    container_name       = "$CONTAINER_NAME"
    key                  = "terraform.tfstate"
  }
}
EOF

echo "Written: infra/backend.tf"


cat > "$(dirname "$0")/terraform.tfvars" <<EOF
# Auto-generated by setup.sh, do not add sensitive values here.
project_name    = "$PROJECT_NAME"
subscription_id = "$SUBSCRIPTION_ID"
location        = "$LOCATION"
EOF

echo "Written: infra/terraform.tfvars"

sed -i '/backend\.tf/d'       "$(dirname "$0")/.gitignore"
sed -i '/terraform\.tfvars/d' "$(dirname "$0")/.gitignore"

git -C .. rm --cached infra/backend.tf       2>/dev/null || true
git -C .. rm --cached infra/terraform.tfvars 2>/dev/null || true

echo "Removed backend.tf and terraform.tfvars from .gitignore"

cd "$(dirname "$0")"
mise x -- terraform init -reconfigure

echo ""
echo "Done. Run 'terraform plan' to preview changes (or 'mise x -- terraform plan' if mise isn't active in your shell)."

